/**
 * mbaobao.com Inc.
 * Copyright (c) 2012 All Rights Reserved.
 */
package com.mbaoabo.test.dao;

import java.util.List;
import java.lang.Integer;
import com.mbaoabo.test.bean.User;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"--kuci
 *
 * Generated by <tt>Tabl2Bean</tt> on 2012-07-25 22:42:41.052.
 *
 * @author kuci@mbaobao.com
 * @version v1.0 2012-07-25 22:42:41.052 $
 */

public interface UserDao {

	public Integer insert(User user);
	
	public Integer update(User user);
	
	public Integer getUserCount(User param);
	
	public List<User> findUsersByPage(User param,Integer offset,Integer rows);
	
	public Integer deleteByPrimary(Integer id);
	
}